{% set name = "types-frozendict" %}
{% set version = "2.0.2" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/types-frozendict-{{ version }}.tar.gz
  sha256: 93bec7db84b1f65bb2c702a45af171d75bcaa7e687ad5f3cfcd839bfaaea91a3

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - python >=3.6

test:
  commands:
    - test -f $SP_DIR/frozendict-stubs/__init__.pyi


about:
  home: https://github.com/python/typeshed
  summary: Typing stubs for frozendict
  license: Apache-2.0 AND MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - fhoehle
    - conda-forge/mypy
