{% set name = "types-frozendict" %}
{% set version = "0.1.6" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/types-frozendict-{{ version }}.tar.gz
  sha256: 16d8cbc8f8be3194851e0cea5b2ce5a00d1a3efd9a9bb730ff0299d43553a1a2

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - python >=3.6

test:
  commands:
    - test -f $SP_DIR/frozendict-stubs/__init__.pyi


about:
  home: https://github.com/python/typeshed
  summary: Typing stubs for frozendict
  license: Apache-2.0 AND MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - fhoehle
    - conda-forge/mypy
